<?php

namespace AppBundle\Repository;

/**
 * RequesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequesRepository extends \Doctrine\ORM\EntityRepository
{
}
