<?php

namespace AppBundle\Repository;

/**
 * RoolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoolsRepository extends \Doctrine\ORM\EntityRepository
{
}
